### ISSUE TITLE
protoc issue ubuntu 20, python3.8, venv

### ISSUE THREAD

**Issue by johnfelipe** [eric-martinet/DataViz_Streamlit_PW5_T1#2]
```
(venv) root@ubuntu20:~/DataViz_Streamlit_PW5_T1# streamlit run streamlit_dataviz.py
Traceback (most recent call last):
  File "/root/DataViz_Streamlit_PW5_T1/venv/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/root/DataViz_Streamlit_PW5_T1/venv/lib/python3.8/site-packages/streamlit/__init__.py", line 48, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "/root/DataViz_Streamlit_PW5_T1/venv/lib/python3.8/site-packages/streamlit/proto/RootContainer_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/root/DataViz_Streamlit_PW5_T1/venv/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

**Comment by johnfelipe** [comment]
```bash
pip3 install --upgrade protobuf==3.20.0
pip3 install click==7.1.2

```
solved
